Update github release workflow
ballerina-platform/module-ballerina-xslt pull request #13
Opened 2020-09-21 14:20 UTC by Bhashinee

## Purpose
$subject.

2020-09-21 17:07 UTC, niveathika requested changes

2020-09-21 17:07 UTC, niveathika commented on .github/workflows/publish-release.yml
> +          curl --request POST 'https://api.github.com/repos/ballerina-platform/module-ballerina-sql/releases' \
```suggestion
          curl --request POST 'https://api.github.com/repos/ballerina-platform/module-ballerina-xslt/releases' \
```

2020-09-21 17:07 UTC, niveathika commented on .github/workflows/publish-release.yml
> +             "name": "module-ballerina-sql-v'"$VERSION"'"
```suggestion
             "name": "module-ballerina-xslt-v'"$VERSION"'"
```

2020-09-22 03:13 UTC, niveathika commented on .github/workflows/publish-release.yml
> +            bin/hub pull-request -m "[Automated] Sync master after "$VERSION" release"
wrong indentation

2020-09-22 03:32 UTC, Bhashinee commented on .github/workflows/publish-release.yml
> +            bin/hub pull-request -m "[Automated] Sync master after "$VERSION" release"
Fixed indentation

2020-09-22 03:39 UTC, niveathika approved these changes

2020-09-22 03:39 UTC, merged